apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: evennia
  namespace: evennia
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: evennia
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
